### ISSUE TITLE
Uploaded samples not showing up for other users

### ISSUE THREAD

**Issue by jhcagaoan** [kaythomas0/noisedash#38]
Hi! 

I've been playing around with the project and have it deployed in docker. I uploaded samples from one user, however, said samples do not show up for other users.

I tried restarting the container but the issue still persists.

Screenshot for user 1 who uploaded samples:

![IMG_20220928_073413](https://user-images.githubusercontent.com/46042129/192655869-69c65393-a535-4dd4-b099-43f8b13ae518.jpg)

Screenshot for user 2:

![IMG_20220928_073524](https://user-images.githubusercontent.com/46042129/192655895-16c4de84-99e2-4269-8931-21243cd97d69.jpg)

I appreciate the project btw, cheers!

**Comment by kaythomas0** [comment]
Hello!

This is actually by design, but you bring up a good point. When I first conceptualized uploadable samples, I thought it made sense to have them be unique to users, because I assumed it might be annoying to see samples you didn't personally upload and may not want. That being said, as time has gone on, I think it does make more sense to have samples shared between all users, because the process of finding samples can be tedious and this would alleviate some of that if some other user already uploaded useful samples.

I'm not sure whether it would make sense to force all samples to be visible to all users, or to have an option to share your sample with all users when you upload it? Either way, I will work on implementing some form of sample sharing. Thanks for bringing this up!

**Comment by jhcagaoan** [comment]
Ohh, I see got this!

I think it may be a good idea to keep the "samples uploaded by the user should only be seen by that user". Then any samples uploaded by the admin account only become visible to all users. 

It also might be a good idea to change the prompt on the upload samples to make the user experience much more intuitive, at least while this issue hasn't been finalized yet.
![image](https://user-images.githubusercontent.com/46042129/193421216-843e6e39-7d64-4f55-857b-746f4ac79483.png)

Just throwing out ideas in case you can come up with something better too. Cheers!
